name: Update release

on:
  repository_dispatch:
    types: [update-github-release]


jobs:
  Update_GitHub_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/TestingInapp@v2

      - name: Update release for ${{ github.event.client_payload.ReleaseBranchName }}
        uses: actions/github-script@v2
        with:

